### ISSUE TITLE
Grid effect

### ISSUE THREAD

**Issue by martinRenou** [martinRenou/Odysis#11]
We should add a grid effect:

![grid](https://user-images.githubusercontent.com/21197331/54091078-e1369580-437b-11e9-99f8-a223bace4cf8.png)

- It should be a widget
- It should have attributes like `line_color`, `line_width`, `number_lines` and it should be possible to choose on which axes to put lines. With possible values like `x`, `xy`, `xz` and even `xyz`.
- It should not be possible to apply it after glyph effects (2-D vectors).
- A warp followed by a grid effect should not be the same result as a grid followed by a warp effet.
- The grid effect should be computed on the GPU, no buffers created

**Comment by wolfv** [comment]
maybe not number of lines, but `spacing`... or both

**Comment by martinRenou** [comment]
`spacing` is better I agree. And there should be a different spacing for each dimension. The default `spacing_x` could be `bounding_box_x / 10`

**Comment by martinRenou** [comment]
We could definitely allow making a grid that highlights data as well (some kind of iso-lines), in the screenshot the input data for the grid was the `x` and `y` positions, but we could use data linked to the mesh (e.g. temperature, pressure etc...)
