### ISSUE TITLE
Odysis and PyVista

### ISSUE THREAD

**Issue by benbovy** [martinRenou/Odysis#24]
Hi Martin,

I have checked again Odysis and run the notebook examples on jupyterlab, this is really exciting!

I also started using [pyvista](https://github.com/pyvista/pyvista) recently and was impressed by its capabilities. I mostly use pyvista's in-notebook interactive rendering through the ``panel`` backend or ``itkwidgets`` (with jupyter notebook/lab installed either locally or on a headless server). However, both of those solutions have their own limitations.

What I really like in Odysis is its tight integration with ``ipywidgets``,  allowing much flexibility, as shown in the [animation example](https://github.com/martinRenou/Odysis_examples/blob/master/Examples/topography_animation.ipynb). Although I have not investigated much, I doubt this kind of interactive animation (including controls) is possible with pyvista's current notebook rendering.

As PyVista would eventually support multiple notebook plotting backend (https://github.com/pyvista/pyvista/pull/300), I'm wondering, naively, if it would be possible to use Odysis as a plotting backend of PyVista? How much work would it require?

Or perhaps a better approach would be the one used by ``itkwidgets``, i.e., that Odysis supports PyVista mesh objects?  

cc @banesullivan

**Comment by martinRenou** [comment]
Hi Benoit!

Interesting thoughts! I did not know PyVista :) Unfortunately, I don't have time to allocate to Odysis as much as I would like to... There are lots of cleaning that I would like to do in it. Maybe supporting PyVista mesh objects would help in that way? It might allow us to remove the VTK file loading logic.

**Comment by benbovy** [comment]
No worries! Yes, supporting PyVista mesh objects in Odysis might be a good start.

I'm afraid I wouldn't be of great help for javascript things but I guess that adding support for PyVista would rather require some work on the Python side. This is something I could do, but I need to find the time.

**Comment by banesullivan** [comment]
This is interesting, thanks for pinging me @benbovy! It looks like this library already supports loading `vtkUnstructuredGrid` datasets?... PyVista mesh types are subclasses of VTK mesh types so maybe then we could leverage PyVista's ability to cast all mesh types to `pyvista.UnstructuredGrid`s which is a subclass of `vtkUnstructuredGrid` which is already supported. Thus, you could update the `from_vtk` method on the `Mesh` class in this library:

https://github.com/martinRenou/Odysis/blob/eb94343f554d5c13a84af7151d035eb730d75c4f/odysis/odysis.py#L177

to something like:

```py
import vtk
...

    @staticmethod
    def from_vtk(path):
        if isinstance(path, str):
            grid = load_vtk(path)
        elif isinstance(path, vtk.vtkUnstructuredGrid):
            grid = path
        else:
            raise TypeError("Only unstructured grids supported at this time.")

        grid.ComputeBounds()
        bounding_box = grid.GetBounds()

        return Mesh(
            vertices=get_ugrid_vertices(grid),
            triangles=get_ugrid_triangles(grid),
            tetrahedrons=get_ugrid_tetrahedrons(grid),
            data=_grid_data_to_data_widget(get_ugrid_data(grid)),
            bounding_box=bounding_box
        )

...

```

And then cast any PyVista mesh as an unstructured grid and pass that to the `Mesh` class like:

```py
import pyvista as pv
from pyvista import examples

pvmesh = examples.download_st_helens().warp_by_scalar()
ugrid = pvmesh.cast_to_unstructured_grid()

from odysis import scene, Mesh
mesh = Mesh.from_vtk(ugrid)
scene(mesh=mesh)
plot()
```

***Disclaimer: I hacked at this and did not run this locally as I had trouble installing this library so the above code is all pseudo-ish)***

Considering that this library handles numpy arrays for all the geometry and data, it would be near trivial to write converters between PyVista's wrapped VTK types and this libraries types.

**Comment by benbovy** [comment]
Thanks for the code examples @banesullivan, very helpful. I'll give it a try.

> I hacked at this and did not run this locally as I had trouble installing this library so the above code is all pseudo-ish)

I had some troubles too but in the end I got it working (in jupyterlab) after a fresh install in a new conda environment.

**Comment by martinRenou** [comment]
Thanks a lot for looking at this @banesullivan !

I'm interested to know what went wrong when installing Odysis. How could I improve the installation documentation? (your comments will be very useful for other libraries too)

**Comment by banesullivan** [comment]
I’m not sure what exactly went wrong, but I can try again later today and post. Since the package isn’t available on PyPI or conda, I tried pip installing from the master branch and had some very strange errors so I gave up immediately without really looking at it

Are there plans to make this package available on PyPI and conda-forge?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martinRenou** [comment]
> Are there plans to make this package available on PyPI and conda-forge?

Hopefully, this will happen.

Note that you need `nodejs` on your machine/environment for the installation to work. It can be installed from `conda-forge`.
